// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTRUCnmNsO8PCZ3CFCndKdyhFsyU3fkQ',
    appId: '1:731810484924:web:8a12f81a279b51eae136b9',
    messagingSenderId: '731810484924',
    projectId: 'rpch-booking-49ca9',
    authDomain: 'rpch-booking-49ca9.firebaseapp.com',
    storageBucket: 'rpch-booking-49ca9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJCWH2fkbKHrcjdo3xvki8hmKwRmipgvk',
    appId: '1:731810484924:android:a7594b264878b55be136b9',
    messagingSenderId: '731810484924',
    projectId: 'rpch-booking-49ca9',
    storageBucket: 'rpch-booking-49ca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD60UX70YWj1CGuPu_Mj_oU1CO8i2eULGo',
    appId: '1:731810484924:ios:f275865bd8ad7aaee136b9',
    messagingSenderId: '731810484924',
    projectId: 'rpch-booking-49ca9',
    storageBucket: 'rpch-booking-49ca9.appspot.com',
    androidClientId: '731810484924-fslfrs0n4g48o4e96uorjeli1gunhirr.apps.googleusercontent.com',
    iosClientId: '731810484924-b09gpgi3nd9fp6o4scnmltvkik1ugv07.apps.googleusercontent.com',
    iosBundleId: 'com.rpch.rpchbooking',
  );
}
